sudo: required
services:
  - docker

before_install:
  - docker build -t MedSouhayelMachfar/react-docker -f Dockerfile.dev .

script:
  - docker run MedSouhayelMachfar/react-docker npm run test -- --coverage